"""empty message

Revision ID: 20ca3d16d401
Revises: 338b000cdbfe
Create Date: 2020-02-27 10:47:27.441151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ca3d16d401'
down_revision = '338b000cdbfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('employee.id', sa.Integer(), nullable=True),
    sa.Column('department.id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department.id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['employee.id'], ['employee.id'], )
    )
    op.drop_table('link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('department_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id', 'employee_id', 'department_id')
    )
    op.drop_table('links')
    # ### end Alembic commands ###
