"""empty message

Revision ID: 338b000cdbfe
Revises: cd2dad37f638
Create Date: 2020-02-27 10:22:20.445926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338b000cdbfe'
down_revision = 'cd2dad37f638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('link', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('link', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
